#!/bin/bash
# sudo apt install gcc-arm-linux-gnueabihf gcc-arm-linux-gnueabi

arm-linux-gnueabi-gcc \
  -std=c89 \
  -Wall \
  -Werror \
  -Werror=implicit-fallthrough \
  -Werror=strict-prototypes \
  -Wsign-compare \
  -Wsign-conversion \
  -Wunused-parameter \
  -Wuninitialized \
  \
  -Os \
  -fomit-frame-pointer \
  \
  -Wno-sign-conversion \
  \
  z.c -c -o z.o
